export const countriesFake = {
  response: [
    {
      name: "Albania",
      code: "AL",
      flag: "https://media-3.api-sports.io/flags/al.svg",
    },
    {
      name: "Algeria",
      code: "DZ",
      flag: "https://media-2.api-sports.io/flags/dz.svg",
    },
    {
      name: "Andorra",
      code: "AD",
      flag: "https://media-1.api-sports.io/flags/ad.svg",
    },
    {
      name: "Angola",
      code: "AO",
      flag: "https://media-2.api-sports.io/flags/ao.svg",
    },
    {
      name: "Argentina",
      code: "AR",
      flag: "https://media-2.api-sports.io/flags/ar.svg",
    },
    {
      name: "Armenia",
      code: "AM",
      flag: "https://media-3.api-sports.io/flags/am.svg",
    },
    {
      name: "Aruba",
      code: "AW",
      flag: "https://media-1.api-sports.io/flags/aw.svg",
    },
    {
      name: "Australia",
      code: "AU",
      flag: "https://media-1.api-sports.io/flags/au.svg",
    },
    {
      name: "Austria",
      code: "AT",
      flag: "https://media-2.api-sports.io/flags/at.svg",
    },
    {
      name: "Azerbaidjan",
      code: "AZ",
      flag: "https://media-2.api-sports.io/flags/az.svg",
    },
    {
      name: "Bahrain",
      code: "BH",
      flag: "https://media-3.api-sports.io/flags/bh.svg",
    },
    {
      name: "Bangladesh",
      code: "BD",
      flag: "https://media-2.api-sports.io/flags/bd.svg",
    },
    {
      name: "Barbados",
      code: "BB",
      flag: "https://media-1.api-sports.io/flags/bb.svg",
    },
    {
      name: "Belarus",
      code: "BY",
      flag: "https://media-2.api-sports.io/flags/by.svg",
    },
    {
      name: "Belgium",
      code: "BE",
      flag: "https://media-1.api-sports.io/flags/be.svg",
    },
    {
      name: "Belize",
      code: "BZ",
      flag: "https://media-3.api-sports.io/flags/bz.svg",
    },
    {
      name: "Benin",
      code: "BJ",
      flag: "https://media-2.api-sports.io/flags/bj.svg",
    },
    {
      name: "Bermuda",
      code: "BM",
      flag: "https://media-2.api-sports.io/flags/bm.svg",
    },
    {
      name: "Bhutan",
      code: "BT",
      flag: "https://media-1.api-sports.io/flags/bt.svg",
    },
    {
      name: "Bolivia",
      code: "BO",
      flag: "https://media-1.api-sports.io/flags/bo.svg",
    },
    {
      name: "Bosnia",
      code: "BA",
      flag: "https://media-1.api-sports.io/flags/ba.svg",
    },
    {
      name: "Botswana",
      code: "BW",
      flag: "https://media-1.api-sports.io/flags/bw.svg",
    },
    {
      name: "Brazil",
      code: "BR",
      flag: "https://media-3.api-sports.io/flags/br.svg",
    },
    {
      name: "Bulgaria",
      code: "BG",
      flag: "https://media-3.api-sports.io/flags/bg.svg",
    },
    {
      name: "Burkina-Faso",
      code: "BF",
      flag: "https://media-3.api-sports.io/flags/bf.svg",
    },
    {
      name: "Burundi",
      code: "BI",
      flag: "https://media-3.api-sports.io/flags/bi.svg",
    },
    {
      name: "Cambodia",
      code: "KH",
      flag: "https://media-1.api-sports.io/flags/kh.svg",
    },
    {
      name: "Cameroon",
      code: "CM",
      flag: "https://media-1.api-sports.io/flags/cm.svg",
    },
    {
      name: "Canada",
      code: "CA",
      flag: "https://media-1.api-sports.io/flags/ca.svg",
    },
    {
      name: "Chile",
      code: "CL",
      flag: "https://media-2.api-sports.io/flags/cl.svg",
    },
    {
      name: "China",
      code: "CN",
      flag: "https://media-1.api-sports.io/flags/cn.svg",
    },
  ],
};
export const seasonfake = {
  response: [
    2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
    2020, 2021, 2022, 2023, 2024, 2025,
  ],
};

export const leagueFake = {
  response: [
    {
      league: {
        id: 71,
        name: "Serie A",
        type: "League",
        logo: "https://media-2.api-sports.io/football/leagues/71.png",
      },
      country: {
        name: "Brazil",
        code: "BR",
        flag: "https://media-3.api-sports.io/flags/br.svg",
      },
      seasons: [
        {
          year: 2010,
          start: "2010-05-08",
          end: "2010-11-28",
          current: false,
          coverage: {
            fixtures: {
              events: true,
              lineups: true,
              statistics_fixtures: false,
              statistics_players: false,
            },
            standings: true,
            players: true,
            top_scorers: true,
            top_assists: true,
            top_cards: true,
            injuries: false,
            predictions: true,
            odds: false,
          },
        },
      ],
    },
  ],
};

export const teamsFake = {
  response: [
    {
      team: {
        id: 119,
        name: "Internacional",
        code: "INT",
        country: "Brazil",
        founded: 1909,
        national: false,
        logo: "https://media-3.api-sports.io/football/teams/119.png",
      },
      venue: {
        id: 244,
        name: "Estádio José Pinheiro Borda",
        address: "Avenida Padre Cacique 891, Bairro Menino Deus",
        city: "Porto Alegre, Rio Grande do Sul",
        capacity: 50128,
        surface: "grass",
        image: "https://media-3.api-sports.io/football/venues/244.png",
      },
    },
    {
      team: {
        id: 120,
        name: "Botafogo",
        code: "BOT",
        country: "Brazil",
        founded: 1904,
        national: false,
        logo: "https://media-1.api-sports.io/football/teams/120.png",
      },
      venue: {
        id: 218,
        name: "Estádio Nilton Santos",
        address: "Rua Arquias Cordeiro, Engenho de Dentro",
        city: "Rio de Janeiro",
        capacity: 46931,
        surface: "grass",
        image: "https://media-3.api-sports.io/football/venues/218.png",
      },
    },
    {
      team: {
        id: 121,
        name: "Palmeiras",
        code: "PAL",
        country: "Brazil",
        founded: 1914,
        national: false,
        logo: "https://media-3.api-sports.io/football/teams/121.png",
      },
      venue: {
        id: 258,
        name: "Allianz Parque",
        address: "Rua Turiaçu 1840, Perdizes",
        city: "São Paulo, São Paulo",
        capacity: 43713,
        surface: "grass",
        image: "https://media-3.api-sports.io/football/venues/258.png",
      },
    },
    {
      team: {
        id: 124,
        name: "Fluminense",
        code: "FLU",
        country: "Brazil",
        founded: 1902,
        national: false,
        logo: "https://media-3.api-sports.io/football/teams/124.png",
      },
      venue: {
        id: 204,
        name: "Estadio Jornalista Mário Filho (Maracanã)",
        address: "Rua Professor Eurico Rabelo, Maracanã",
        city: "Rio de Janeiro, Rio de Janeiro",
        capacity: 78838,
        surface: "grass",
        image: "https://media-2.api-sports.io/football/venues/204.png",
      },
    },
    {
      team: {
        id: 126,
        name: "Sao Paulo",
        code: "PAU",
        country: "Brazil",
        founded: 1930,
        national: false,
        logo: "https://media-3.api-sports.io/football/teams/126.png",
      },
      venue: {
        id: 269,
        name: "Estádio Cícero Pompeu de Toledo (Morumbi)",
        address: "Praca Roberto Gomes Pedrosa 1, Morumbi",
        city: "São Paulo, São Paulo",
        capacity: 66795,
        surface: "grass",
        image: "https://media-1.api-sports.io/football/venues/269.png",
      },
    },
    {
      team: {
        id: 127,
        name: "Flamengo",
        code: "FLA",
        country: "Brazil",
        founded: 1895,
        national: false,
        logo: "https://media-1.api-sports.io/football/teams/127.png",
      },
      venue: {
        id: 204,
        name: "Estadio Jornalista Mário Filho (Maracanã)",
        address: "Rua Professor Eurico Rabelo, Maracanã",
        city: "Rio de Janeiro, Rio de Janeiro",
        capacity: 78838,
        surface: "grass",
        image: "https://media-3.api-sports.io/football/venues/204.png",
      },
    },
    {
      team: {
        id: 128,
        name: "Santos",
        code: "SAN",
        country: "Brazil",
        founded: 1912,
        national: false,
        logo: "https://media-2.api-sports.io/football/teams/128.png",
      },
      venue: {
        id: 10494,
        name: "Estádio Urbano Caldeira",
        address: "Rue Princesa Isabel 77, Vila Belmiro",
        city: "Santos, São Paulo",
        capacity: 21256,
        surface: "grass",
        image: "https://media-3.api-sports.io/football/venues/10494.png",
      },
    },
    {
      team: {
        id: 129,
        name: "Ceara",
        code: "CEA",
        country: "Brazil",
        founded: 1914,
        national: false,
        logo: "https://media-1.api-sports.io/football/teams/129.png",
      },
      venue: {
        id: 225,
        name: "Estádio Governador Plácido Aderaldo Castelo",
        address: "Avenida Alberto Craveiro, Passaré",
        city: "Fortaleza, Ceará",
        capacity: 63903,
        surface: "grass",
        image: "https://media-3.api-sports.io/football/venues/225.png",
      },
    },
    {
      team: {
        id: 130,
        name: "Gremio",
        code: "GRE",
        country: "Brazil",
        founded: 1903,
        national: false,
        logo: "https://media-1.api-sports.io/football/teams/130.png",
      },
      venue: {
        id: 241,
        name: "Arena do Grêmio",
        address: "Bairro Humaitá",
        city: "Porto Alegre, Rio Grande do Sul",
        capacity: 60540,
        surface: "grass",
        image: "https://media-3.api-sports.io/football/venues/241.png",
      },
    },
    {
      team: {
        id: 131,
        name: "Corinthians",
        code: "COR",
        country: "Brazil",
        founded: 1910,
        national: false,
        logo: "https://media-3.api-sports.io/football/teams/131.png",
      },
      venue: {
        id: 11531,
        name: "Neo Química Arena",
        address: "Avenida Miguel Inácio Curi, 111, Vila Carmosina, Itaquera",
        city: "São Paulo, São Paulo",
        capacity: 49205,
        surface: "grass",
        image: "https://media-2.api-sports.io/football/venues/11531.png",
      },
    },
    {
      team: {
        id: 133,
        name: "Vasco DA Gama",
        code: "VAS",
        country: "Brazil",
        founded: 1898,
        national: false,
        logo: "https://media-1.api-sports.io/football/teams/133.png",
      },
      venue: {
        id: 19377,
        name: "Estádio São Januário",
        address: "Rua Gal Almério de Moura 131, Bairro Vasco da Gama",
        city: "Rio de Janeiro, Rio de Janeiro",
        capacity: 24584,
        surface: "grass",
        image: "https://media-2.api-sports.io/football/venues/19377.png",
      },
    },
    {
      team: {
        id: 134,
        name: "Atletico Paranaense",
        code: "ATL",
        country: "Brazil",
        founded: 1924,
        national: false,
        logo: "https://media-1.api-sports.io/football/teams/134.png",
      },
      venue: {
        id: 10493,
        name: "Arena da Baixada",
        address: "Rua Buenos Aires 1260, Água Verde",
        city: "Curitiba, Paraná",
        capacity: 43981,
        surface: "grass",
        image: "https://media-3.api-sports.io/football/venues/10493.png",
      },
    },
    {
      team: {
        id: 135,
        name: "Cruzeiro",
        code: "CRU",
        country: "Brazil",
        founded: 1921,
        national: false,
        logo: "https://media-2.api-sports.io/football/teams/135.png",
      },
      venue: {
        id: 234,
        name: "Estádio Governador Magalhães Pinto",
        address: "Avenida Antonio Abrahão Carã 1001, Pampulhas",
        city: "Belo Horizonte, Minas Gerais",
        capacity: 62170,
        surface: "grass",
        image: "https://media-1.api-sports.io/football/venues/234.png",
      },
    },
    {
      team: {
        id: 136,
        name: "Vitoria",
        code: "VIT",
        country: "Brazil",
        founded: 1899,
        national: false,
        logo: "https://media-1.api-sports.io/football/teams/136.png",
      },
      venue: {
        id: 281,
        name: "Estádio Manoel Barradas",
        address:
          "Rua Artêmio Castro Valente 1, Bairro Nossa Senhora da Vitória",
        city: "Salvador, Bahia",
        capacity: 35980,
        surface: "grass",
        image: "https://media-1.api-sports.io/football/venues/281.png",
      },
    },
    {
      team: {
        id: 138,
        name: "Guarani Campinas",
        code: "GUA",
        country: "Brazil",
        founded: 1911,
        national: false,
        logo: "https://media-2.api-sports.io/football/teams/138.png",
      },
      venue: {
        id: 242,
        name: "Estádio Brinco de Ouro da Princesa",
        address: "Avenida Imperatriz Tereza Cristina 11, Bairro Jardim Paraíso",
        city: "Campinas, São Paulo",
        capacity: 29130,
        surface: "grass",
        image: "https://media-1.api-sports.io/football/venues/242.png",
      },
    },
    {
      team: {
        id: 144,
        name: "Atletico Goianiense",
        code: "ATL",
        country: "Brazil",
        founded: 1937,
        national: false,
        logo: "https://media-2.api-sports.io/football/teams/144.png",
      },
      venue: {
        id: 211,
        name: "Estádio Antônio Accioly",
        address:
          "Avenida Perimetral 923 / Avenida 24 de Outubro, Bairro Campinas",
        city: "Goiânia, Goiás",
        capacity: 12500,
        surface: "grass",
        image: "https://media-2.api-sports.io/football/venues/211.png",
      },
    },
    {
      team: {
        id: 145,
        name: "Avai",
        code: "AVA",
        country: "Brazil",
        founded: 1923,
        national: false,
        logo: "https://media-3.api-sports.io/football/teams/145.png",
      },
      venue: {
        id: 214,
        name: "Estádio Aderbal Ramos da Silva",
        address: "Avenida Deputado Diomício Freitas 1000, Bairro Carianos",
        city: "Florianópolis, Santa Catarina",
        capacity: 19000,
        surface: "grass",
        image: "https://media-2.api-sports.io/football/venues/214.png",
      },
    },
    {
      team: {
        id: 151,
        name: "Goias",
        code: "GOI",
        country: "Brazil",
        founded: 1943,
        national: false,
        logo: "https://media-1.api-sports.io/football/teams/151.png",
      },
      venue: {
        id: 240,
        name: "Estádio de Hailé Pinheiro",
        address: "Avenida Edmundo Pinheiro de Abreu 721, Setor Bela Vista",
        city: "Goiânia, Goiás",
        capacity: 14525,
        surface: "grass",
        image: "https://media-2.api-sports.io/football/venues/240.png",
      },
    },
    {
      team: {
        id: 1062,
        name: "Atletico-MG",
        code: "ATL",
        country: "Brazil",
        founded: 1908,
        national: false,
        logo: "https://media-1.api-sports.io/football/teams/1062.png",
      },
      venue: {
        id: 206,
        name: "Estádio Raimundo Sampaio",
        address: "Avenida Ismênia Tunes, Bairro Horto",
        city: "Belo Horizonte, Minas Gerais",
        capacity: 23018,
        surface: "grass",
        image: "https://media-2.api-sports.io/football/venues/206.png",
      },
    },
    {
      team: {
        id: 4655,
        name: "Grêmio Barueri",
        code: "BAR",
        country: "Brazil",
        founded: 1989,
        national: false,
        logo: "https://media-2.api-sports.io/football/teams/4655.png",
      },
      venue: {
        id: 2939,
        name: "Estádio Municipal Prefeito José Liberatti",
        address: "Rua Júlio Adão",
        city: "Osasco, São Paulo",
        capacity: 12900,
        surface: "grass",
        image: "https://media-1.api-sports.io/football/venues/2939.png",
      },
    },
  ],
};
export const playerFake = {
  response: [
    {
      player: {
        id: 77652,
        name: "Marquinhos",
        firstname: "Marcos Vicente",
        lastname: "dos Santos",
        age: 38,
        birth: {
          date: "1981-09-29",
          place: "Biguaçu",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "183 cm",
        weight: "85 kg",
        injured: false,
        photo: "https://media-2.api-sports.io/football/players/77652.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-2.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-2.api-sports.io/football/leagues/71.png",
            flag: "https://media-1.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 28,
            lineups: 25,
            minutes: 1847,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 3,
            out: 18,
            bench: 3,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 1,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 1,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 80293,
        name: "Marcos Arouca da Silva",
        firstname: "Marcos",
        lastname: "Arouca da Silva",
        age: 35,
        birth: {
          date: "1986-08-11",
          place: "Duas Barras",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "171 cm",
        weight: "74 kg",
        injured: false,
        photo: "https://media-3.api-sports.io/football/players/80293.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-1.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-2.api-sports.io/football/leagues/71.png",
            flag: "https://media-2.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 28,
            lineups: 28,
            minutes: 2438,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 2,
            bench: 0,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 9,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 49851,
        name: "Robinho",
        firstname: "Róbson",
        lastname: "de Souza",
        age: 37,
        birth: {
          date: "1984-01-25",
          place: "São Vicente",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "172 cm",
        weight: "60 kg",
        injured: false,
        photo: "https://media-3.api-sports.io/football/players/49851.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-1.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-2.api-sports.io/football/leagues/71.png",
            flag: "https://media-2.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 2,
            lineups: 2,
            minutes: 180,
            number: null,
            position: "Attacker",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 0,
            bench: 0,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 114563,
        name: "Manoel Messias Barbosa da Silva",
        firstname: "Manoel Messias",
        lastname: "Barbosa da Silva",
        age: 32,
        birth: {
          date: "1985-12-25",
          place: "Codó",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "171 cm",
        weight: "71 kg",
        injured: false,
        photo: "https://media-2.api-sports.io/football/players/114563.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-2.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-1.api-sports.io/football/leagues/71.png",
            flag: "https://media-3.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 18,
            lineups: 11,
            minutes: 1104,
            number: null,
            position: "Defender",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 7,
            out: 1,
            bench: 14,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 2,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 2,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 10464,
        name: "Madson Formagini Caridade",
        firstname: "Madson",
        lastname: "Formagini Caridade",
        age: 34,
        birth: {
          date: "1986-05-21",
          place: "Volta Redonda",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "158 cm",
        weight: "68 kg",
        injured: false,
        photo: "https://media-3.api-sports.io/football/players/10464.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-2.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-1.api-sports.io/football/leagues/71.png",
            flag: "https://media-1.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 18,
            lineups: 5,
            minutes: 721,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 13,
            out: 4,
            bench: 16,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 2,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 1,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 115738,
        name: "Rodrigo Cesar Castro Cabral",
        firstname: "Rodrigo Cesar",
        lastname: "Castro Cabral",
        age: 34,
        birth: {
          date: "1982-02-05",
          place: "Guarapuava",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "179 cm",
        weight: "78 kg",
        injured: false,
        photo: "https://media-2.api-sports.io/football/players/115738.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-1.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-3.api-sports.io/football/leagues/71.png",
            flag: "https://media-1.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 14,
            lineups: 11,
            minutes: 996,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 3,
            out: 2,
            bench: 7,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 2,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 8,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 77723,
        name: "Adriano Bispo Bispo dos Santos",
        firstname: "Adriano Bispo",
        lastname: "Bispo dos Santos",
        age: 34,
        birth: {
          date: "1987-05-29",
          place: "São Vicente",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "171 cm",
        weight: "71 kg",
        injured: false,
        photo: "https://media-1.api-sports.io/football/players/77723.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-2.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-1.api-sports.io/football/leagues/71.png",
            flag: "https://media-2.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 5,
            lineups: 4,
            minutes: 321,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 1,
            bench: 5,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 3,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 114409,
        name: "Rodrigo Marcos dos Santos",
        firstname: "Rodrigo Marcos",
        lastname: "dos Santos",
        age: 31,
        birth: {
          date: "1986-06-16",
          place: "Curitiba",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "189 cm",
        weight: "83 kg",
        injured: false,
        photo: "https://media-1.api-sports.io/football/players/114409.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-3.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-1.api-sports.io/football/leagues/71.png",
            flag: "https://media-3.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 1,
            lineups: 0,
            minutes: 78,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 0,
            bench: 2,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 96349,
        name: "Marcos Vinicius Gomes de Lima",
        firstname: "Marcos Vinicius",
        lastname: "Gomes de Lima",
        age: 29,
        birth: {
          date: "1992-12-22",
          place: "Rialma",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "179 cm",
        weight: "75 kg",
        injured: false,
        photo: "https://media-1.api-sports.io/football/players/96349.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-3.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-1.api-sports.io/football/leagues/71.png",
            flag: "https://media-3.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 1,
            lineups: 0,
            minutes: 11,
            number: null,
            position: "Attacker",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 0,
            bench: 2,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 9915,
        name: "Edu Dracena",
        firstname: "Eduardo",
        lastname: "Luis Abonizio Souza",
        age: 39,
        birth: {
          date: "1981-05-18",
          place: "Dracena",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "187 cm",
        weight: "81 kg",
        injured: false,
        photo: "https://media-1.api-sports.io/football/players/9915.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-3.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-3.api-sports.io/football/leagues/71.png",
            flag: "https://media-2.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 28,
            lineups: 28,
            minutes: 2492,
            number: null,
            position: "Defender",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 1,
            bench: 0,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 2,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 10,
            yellowred: 1,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 77746,
        name: "Keirrison de Souza Carneiro",
        firstname: "Keirrison",
        lastname: "de Souza Carneiro",
        age: 30,
        birth: {
          date: "1988-12-03",
          place: "Dourados",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "184 cm",
        weight: "80 kg",
        injured: false,
        photo: "https://media-3.api-sports.io/football/players/77746.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-3.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-2.api-sports.io/football/leagues/71.png",
            flag: "https://media-2.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 11,
            lineups: 9,
            minutes: 631,
            number: null,
            position: "Attacker",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 2,
            out: 8,
            bench: 5,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 3,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 3,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 114534,
        name: "Marcel Augusto Ortolan",
        firstname: "Marcel Augusto",
        lastname: "Ortolan",
        age: 33,
        birth: {
          date: "1981-11-12",
          place: "Mirassol",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "187 cm",
        weight: "86 kg",
        injured: false,
        photo: "https://media-3.api-sports.io/football/players/114534.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-1.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-3.api-sports.io/football/leagues/71.png",
            flag: "https://media-3.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 24,
            lineups: 10,
            minutes: 1005,
            number: null,
            position: "Attacker",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 14,
            out: 6,
            bench: 18,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 7,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 2,
            yellowred: 0,
            red: 1,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 80731,
        name: "Moisés Ferreira Gomes",
        firstname: "Moisés",
        lastname: "Ferreira Gomes",
        age: 32,
        birth: {
          date: "1989-05-15",
          place: "Belém",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "175 cm",
        weight: "65 kg",
        injured: false,
        photo: "https://media-2.api-sports.io/football/players/80731.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-1.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-1.api-sports.io/football/leagues/71.png",
            flag: "https://media-1.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 1,
            lineups: 0,
            minutes: 9,
            number: null,
            position: "Attacker",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 0,
            bench: 4,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 41915,
        name: "Breitner",
        firstname: "Overath Breitner",
        lastname: "da Silva Medina",
        age: 32,
        birth: {
          date: "1989-09-09",
          place: "Barcelona",
          country: "Venezuela",
        },
        nationality: "Brazil",
        height: "170 cm",
        weight: "63 kg",
        injured: false,
        photo: "https://media-3.api-sports.io/football/players/41915.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-2.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-2.api-sports.io/football/leagues/71.png",
            flag: "https://media-1.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 11,
            lineups: 0,
            minutes: 199,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 11,
            out: 0,
            bench: 16,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 115650,
        name: "Rodrigo Possebon",
        firstname: "Rodrigo",
        lastname: "Pereira Possebon",
        age: 32,
        birth: {
          date: "1989-02-13",
          place: "Sapucaia do Sul",
          country: "Brazil",
        },
        nationality: "Italy",
        height: "184 cm",
        weight: "77 kg",
        injured: false,
        photo: "https://media-1.api-sports.io/football/players/115650.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-2.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-3.api-sports.io/football/leagues/71.png",
            flag: "https://media-3.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 3,
            lineups: 3,
            minutes: 215,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 2,
            bench: 1,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 1,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 80356,
        name: "Bruno Rodrigo Fenelon Palomo",
        firstname: "Bruno Rodrigo",
        lastname: "Fenelon Palomo",
        age: 32,
        birth: {
          date: "1985-04-12",
          place: "Andradina",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "186 cm",
        weight: "80 kg",
        injured: false,
        photo: "https://media-1.api-sports.io/football/players/80356.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-1.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-1.api-sports.io/football/leagues/71.png",
            flag: "https://media-3.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 1,
            lineups: 1,
            minutes: 66,
            number: null,
            position: "Defender",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 1,
            bench: 0,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 145775,
        name: "André Lucas Ferlini",
        firstname: "André",
        lastname: "Lucas Ferlini",
        age: 30,
        birth: {
          date: "1992-02-06",
          place: "Votuporanga",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "196 cm",
        weight: "90 kg",
        injured: false,
        photo: "https://media-1.api-sports.io/football/players/145775.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-2.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-3.api-sports.io/football/leagues/71.png",
            flag: "https://media-3.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 1,
            lineups: 0,
            minutes: 15,
            number: null,
            position: "Goalkeeper",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 1,
            bench: 1,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 115625,
        name: "Roberto Brum",
        firstname: "Roberto",
        lastname: "Brum Vallado",
        age: 43,
        birth: {
          date: "1978-07-07",
          place: "São Gonçalo",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "176 cm",
        weight: "74 kg",
        injured: false,
        photo: "https://media-1.api-sports.io/football/players/115625.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-2.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-3.api-sports.io/football/leagues/71.png",
            flag: "https://media-2.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 16,
            lineups: 14,
            minutes: 1097,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 2,
            out: 5,
            bench: 9,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 3,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 115809,
        name: "Jefferson Souza",
        firstname: "Jefferson Luiz",
        lastname: "Nascimento de Souza",
        age: 32,
        birth: {
          date: "1989-05-27",
          place: "Padre Miguel",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "174 cm",
        weight: "69 kg",
        injured: false,
        photo: "https://media-1.api-sports.io/football/players/115809.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-3.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-2.api-sports.io/football/leagues/71.png",
            flag: "https://media-3.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 1,
            lineups: 0,
            minutes: 10,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 0,
            bench: 4,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 115845,
        name: "Giovanni Silva de Oliveira",
        firstname: "Giovanni",
        lastname: "Silva de Oliveira",
        age: 41,
        birth: {
          date: "1972-4-2",
          place: "Belem",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "190 cm",
        weight: "84 kg",
        injured: false,
        photo: "https://media-2.api-sports.io/football/players/115845.png",
      },
      statistics: [
        {
          team: {
            id: 128,
            name: "Santos",
            logo: "https://media-2.api-sports.io/football/teams/128.png",
          },
          league: {
            id: 71,
            name: "Serie A",
            country: "Brazil",
            logo: "https://media-2.api-sports.io/football/leagues/71.png",
            flag: "https://media-3.api-sports.io/flags/br.svg",
            season: 2010,
          },
          games: {
            appearences: 1,
            lineups: 0,
            minutes: 5,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 0,
            bench: 1,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: 0,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
  ],
};
